TEXT_REGISTER = "Register"

TEXT_FRIST_NAME = "Mr.Tester"
TEXT_LAST_NAME = "Programmer"
TEXT_NICK_NAME = "Test"
TEXT_USERNAME = "tester01"
TEXT_PASSWORD = "pass1234"
TEXT_CONFIRME_PASSWORD = "pass1234"
TEXT_TELEPHONE = "0123456789"
TEXT_ADDRESS = "local at you PC"
TEXT_EMAIL = "tester@email.com"
TEXT_BIRTHDAY = ""
TEXT_CONFIRME_PASSWORD_UNLIKE = "tester01"
TEXT_PASSWORD_NOT_MATCH = "Password and confirme Password not match"

TEXT_REGISTER_SUCCESS = "Register success"

LOCATOR_BTN_REGISTER = "//html/body/div/form[2]/input"
LOCATOR_BTN_REGISTER_PAGE = "//html/body/form/div[1]/button"
LOCATOR_BTN_LOG_IN_REGISTER_PAGE = "//html/body/form/input"

LOCATOR_FRIST_NAME = "//*[@id='fname']"
LOCATOR_LAST_NAME = "//*[@id='lname']"
LOCATOR_NICK_NAME = "//*[@id='nname']"
LOCATOR_USERNAME = "//*[@id='user']"
LOCATOR_PASSWORD = "//*[@id='psw']"
LOCATOR_CONFIRME_PASSWORD = "//*[@id='psw_re']"
LOCATOR_TELEPHONE = "//*[@id='telephone']"
LOCATOR_ADDRESS = "//*[@id='address']"
LOCATOR_EMAIL = "//*[@id='email']"
LOCATOR_BIRTHDAY = "//*[@id='birthday']"
LOCATOR_RULE = "//*[@id='rule']"
